### PR TITLE
KCP-78 - model visualization updates

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-78

### CODE REVIEW

**Comment by hanharrison92** [comment]
The icon, bar and area looks great. Could we have the same order for the table and text options (should be gray/death, white/recuurence, turquoise/survived with no recurrence).

**Comment by hanharrison92** [comment]
Text options for table and text display for survival with no recurrence should be: "X% of patients are living cancer free"

**Comment by hanharrison92** [comment]
Fab, all requirements now satisfied. It's looking great 👍

**Comment by phuhgh** [comment]
All deployed, everything seems in order

There's an annoying issue in the CI, it's showing the pull request action on the commit as failing. That shouldn't even be listed on the commit (that it's failing is odd to, but it's odder that it's even running again).

All of the important checks are passing though, I'll address it in the next round of changes

**Comment by hanharrison92** [comment]
That's great! Thank you for pushing this through in time for our workshops.

**Pull request merged**
