### PR TITLE
KCP-79 - Printout changes

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-78
https://wintoncentre.atlassian.net/browse/KCP-79

### CODE REVIEW

**Comment by phuhgh** [comment]
@hanharrison92 this should address the remaining issues in both KCP-78 and KCP-79 now.

One thing I'm not clear on is the wording of the textual representations (died from other causes / died due to other causes), the document mentions both.

**Comment by phuhgh** [comment]
One other thing I need to do before this gets merged is test on mac / safari etc

**Comment by hanharrison92** [comment]
I'm happy with how this has been done, looks like you have used "died from other causes" everywhere. That's probably slightly better phrasing.

**Comment by hanharrison92** [comment]
Otherwise, this satifies all the requirements I have for the printout in this set of changes. I'm also happy with the updates to the legends/labelling for the main plots.

**Comment by phuhgh** [comment]
Firefox looks the same, but Safari mysteriously prints a blank 3rd page. The content on the second page is nowhere near the bottom of the page, so I'm not sure what's going on with that.

 You can tell it to print only up to page 2, so I don't think that's a deal breaker anyway

**Comment by phuhgh** [comment]
https://wintoncentre.atlassian.net/browse/KCP-84

**Pull request merged**
