### PR TITLE
KCP-90 - update printout based on feedback

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-90

### CODE REVIEW

**Comment by phuhgh** [comment]
There was a minor difference in text between this and KCP-88 for the regional lymph node status, the change here overwrites that of KCP-88:

image

**Comment by hanharrison92** [comment]
Hi, this is looking good. Couple of quick requests for changes: 

- I made a typo in the bolding of the first paragraph, currently "**is 3%**" should be "is **3%**"
- Now that I see how the Results/Leibovich score lines at the top of page 1 look with the new formatting, I would prefer instead: "Results: Intermediate Risk, Leibovich Score 3 out of 11" all on one line.

**Comment by phuhgh** [comment]
the first version I pushed wasn't quite right, it will take a little while to referesh

**Comment by hanharrison92** [comment]
Thanks - could you remove the colon after Leibovich score?

**Comment by phuhgh** [comment]
it should be correct now

**Comment by hanharrison92** [comment]
That is perfect.

**Pull request merged**
