### PR TITLE
KCP-76 - update model inputs page

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-76

The numeric control is addressed in KCP-81

### CODE REVIEW

**Comment by hanharrison92** [comment]
Adding free text to the age input box is a bit buggy in the preview. Seems to auto jump to 25 and then needs corrected. If changing the age after results are calculated it is not possible to re-enter age without clearing all inputs.

**Comment by hanharrison92** [comment]
Also - could the text on the age warning "Age must be between 25 and 85 years" be a couple of font sizes smaller and in italics?

**Comment by phuhgh** [comment]
@hanharrison92 that's fixed in https://wintoncentre.atlassian.net/browse/KCP-81

re font etc, yes that would make sense, I'll update this

**Comment by hanharrison92** [comment]
Update to font (size and italics) is perfect.

**Comment by phuhgh** [comment]
merged in https://github.com/WintonCentre/kcp/pull/35

**Pull request closed without merging**
