### PR TITLE
KCP-50 - rework printout

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-50

This has a fair amount of hard-coding in the string building. In the event it needs to be more flexible, it will need to be reworked to use string interpolation. I haven't been able to find a good cross browser solution for page numbers so far, so I've omitted it. In safari there's an extra checkbox that needs ticking (I don't have a mac to hand so I'll look for it later). I'll open a issue to update the instructions in the print dialog.

### CODE REVIEW

**Comment by hanharrison92** [comment]
Hi,
I'm pretty happy with this. Only minor change, is could we have both dates in the same format dd/mm/yyyy? Will raise a jira issue for this. 

I've also sent an example round to a couple of collegues (including a clinician who would hypothetically be giving this to patients) as it is one of the more substantial changes we are making - will merge and comment with any feedback from them by the end of the day.

**Comment by phuhgh** [comment]
Whoops, yeah absolutely. I'll address it in https://github.com/WintonCentre/kcp/pull/16, no need to raise a ticket for it. That's only really needed when there's a large stack of branches to merge, it can be quite a lot of work to rebase (especially if changes conflict)

**Comment by hanharrison92** [comment]
Sorry - won't create issues for minor changes again! I got a bit of feedback on the printout from my collegues. 
1. The area graph looks a bit squished to the left of its box - can it be spread out (I am aware that I have no idea if this is straightforward or a massive pain)?
2. Minor text changes to the second page (bit annoying this is not the first review of this design...!), will send an updated copy as a text document.

**Comment by hanharrison92** [comment]
3. final request (not really about the printout) is that can we add a line to the box where users input their data (name etc.) stating that we don't store this? So first line would read "All of the following inputs are optional. Your personal data will not be stored by this website."

Let me know which of these (if any) you want me to raise as new issues in Jira.

**Comment by phuhgh** [comment]
I can address all of those here, the area chart is "delicate", but I've updated it by hand in the browser so it's definitely possible

**Comment by phuhgh** [comment]
I noticed a bug while implementing that, embarrassingly it was using the default value for the description, not the selected value. I've fixed that too

**Comment by hanharrison92** [comment]
1. Could you remove the second colon in the title (after Leibovich Score)?
2. Could you indent the personalised statements on the second page (e.g. Your tumour stage...)?

**Comment by phuhgh** [comment]
The indent should already be in (you might need to ctrl-f5), I'll remove the colon

**Comment by hanharrison92** [comment]
Jack - thanks, that's looking perfect now!

**Pull request merged**
