### PR TITLE
KCP-61 technical page

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-61
https://wintoncentre.atlassian.net/browse/KCP-64

I removed the paragraph mentioning the PWA functionality, as it was removed.

### CODE REVIEW

**Comment by hanharrison92** [comment]
Couple of small changes to the references to the publications (my fault as I didn't realise till I saw the implementation that I had been inconsistent). Will raise a Jira issue.

**Comment by phuhgh** [comment]
I've included KCP-61 in this PR, as they're in the same file. I don't see any reference to BJUI review paper (2) on that page, did I miss something?

**Comment by hanharrison92** [comment]
Sorry don't think I was very clear previously. 

The reference to the Leibovich paper is at the end of the model development section ("Further information is provided in the paper published in the journal Cancer, March 2003" -> "Further information is provided in the model development paper (published 2003)"

While the reference in the Model Validation section was previously to the BJUI review paper (and should be changed back to this). "More details can be found in this review paper (published in 2021). "

**Comment by hanharrison92** [comment]
That's perfect now - thanks.

**Pull request merged**
