### PR TITLE
KCP-89 - outputs

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-89

### CODE REVIEW

**Comment by hanharrison92** [comment]
The icon array image is perfect!

**Comment by hanharrison92** [comment]
Happy with the %label removal from the bar/area - but could you put the death from other causes back in the legend at the bottom? Just so these figures have an explanation of what the grey means even if we don't report the exact number.

**Comment by hanharrison92** [comment]
The font change for the L/I/H Risk and Leibovich Score is perfect.

**Comment by phuhgh** [comment]
@hanharrison92 If I understood your meaning correctly, it should all be there now

**Comment by hanharrison92** [comment]
Thanks for adding the legend item back in. On the legend, could you move death from other causes to the bottom, so that the legned order is recurrence, survival, death from other causes?

**Comment by hanharrison92** [comment]
Great - the changes to how death from other causes is presented are exactly as I imagined now.

**Pull request merged**
