### PR TITLE
KCP-74 - update technical section

### PR DESCRIPTION
**Pull request by phuhgh**
https://wintoncentre.atlassian.net/browse/KCP-74

### CODE REVIEW

**Comment by phuhgh** [comment]
@hanharrison92 please give this a good look over, fair chance I've missed something

**Comment by phuhgh** [comment]
I spotted (what I take to be) a few typos:
- repeated section
- rogue hash at end of equation

I wasn't sure if the following was intentional:

`The estimated cumulative recurrence hazard for a given is given by;`

was that supposed to be a colon? I forget the rules around semicolons with lists

**Comment by hanharrison92** [comment]
Thank for the typo spotting. The cumulative hazard sentence should be: "The estimated cumulative recurrence hazard is given by:"

**Comment by hanharrison92** [comment]
Spotted another typo (our error). Where is says "UK/England" in the 4th and 5th paragraphs, this should be "England".

**Comment by hanharrison92** [comment]
Spotted another typo (our error). Where is says "UK/England" in the 4th and "UK/English" in the 5th paragraphs, this should be "England" and "English".

**Comment by hanharrison92** [comment]
Otherwise I'm happy with the technical section, the equations are all rendered as I expected. I noticed that the subscript text is hard to read in some places, but I will note that down as an issue to address in a future update.

**Comment by phuhgh** [comment]
Speaking of typos 😅

**Comment by hanharrison92** [comment]
Great, happy with those fixes.

**Pull request merged**
